apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  namespace: emqx
  labels:
    app: emqx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      serviceAccountName: emqx
      containers:
      - name: emqx
        image: emqx/emqx:5.6.0
        ports:
        - name: mqtt
          containerPort: 1883
        - name: dashboard
          containerPort: 18083
        - name: epmd
          containerPort: 4369
        - name: rpc
          containerPort: 5369
        - name: cluster
          containerPort: 4370
        env:
        - name: EMQX_CLUSTER__DISCOVERY
          value: "kubernetes"
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: "emqx"
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: "emqx"
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: "emqx"
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: "ip"
